name: Deploy to Google Play

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Decode Keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: |
          echo $KEYSTORE_FILE | base64 --decode --ignore-garbage > keystore.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release Bundle
        run: ./gradlew :app:bundleRelease --stacktrace

      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload to Google Play (Internal)
        if: github.ref == 'refs/heads/main'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.allensandiego.notepad
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          status: completed
          inAppUpdatePriority: 2